export default interface FullApiInfo {
	id: string;
	url: string;
	createdAt: Date;
	updatedAt: Date;
	language: string;
}

// [
//   {
//     "id": 215359537,
//     "node_id": "MDEwOlJlcG9zaXRvcnkyMTUzNTk1Mzc=",
//     "name": "cv",
//     "full_name": "rubengglez/cv",
//     "private": false,
//     "owner": {
//       "login": "rubengglez",
//       "id": 7514422,
//       "node_id": "MDQ6VXNlcjc1MTQ0MjI=",
//       "avatar_url": "https://avatars1.githubusercontent.com/u/7514422?v=4",
//       "gravatar_id": "",
//       "url": "https://api.github.com/users/rubengglez",
//       "html_url": "https://github.com/rubengglez",
//       "followers_url": "https://api.github.com/users/rubengglez/followers",
//       "following_url": "https://api.github.com/users/rubengglez/following{/other_user}",
//       "gists_url": "https://api.github.com/users/rubengglez/gists{/gist_id}",
//       "starred_url": "https://api.github.com/users/rubengglez/starred{/owner}{/repo}",
//       "subscriptions_url": "https://api.github.com/users/rubengglez/subscriptions",
//       "organizations_url": "https://api.github.com/users/rubengglez/orgs",
//       "repos_url": "https://api.github.com/users/rubengglez/repos",
//       "events_url": "https://api.github.com/users/rubengglez/events{/privacy}",
//       "received_events_url": "https://api.github.com/users/rubengglez/received_events",
//       "type": "User",
//       "site_admin": false
//     },
//     "html_url": "https://github.com/rubengglez/cv",
//     "description": "My curriculum vitae. ",
//     "fork": false,
//     "url": "https://api.github.com/repos/rubengglez/cv",
//     "forks_url": "https://api.github.com/repos/rubengglez/cv/forks",
//     "keys_url": "https://api.github.com/repos/rubengglez/cv/keys{/key_id}",
//     "collaborators_url": "https://api.github.com/repos/rubengglez/cv/collaborators{/collaborator}",
//     "teams_url": "https://api.github.com/repos/rubengglez/cv/teams",
//     "hooks_url": "https://api.github.com/repos/rubengglez/cv/hooks",
//     "issue_events_url": "https://api.github.com/repos/rubengglez/cv/issues/events{/number}",
//     "events_url": "https://api.github.com/repos/rubengglez/cv/events",
//     "assignees_url": "https://api.github.com/repos/rubengglez/cv/assignees{/user}",
//     "branches_url": "https://api.github.com/repos/rubengglez/cv/branches{/branch}",
//     "tags_url": "https://api.github.com/repos/rubengglez/cv/tags",
//     "blobs_url": "https://api.github.com/repos/rubengglez/cv/git/blobs{/sha}",
//     "git_tags_url": "https://api.github.com/repos/rubengglez/cv/git/tags{/sha}",
//     "git_refs_url": "https://api.github.com/repos/rubengglez/cv/git/refs{/sha}",
//     "trees_url": "https://api.github.com/repos/rubengglez/cv/git/trees{/sha}",
//     "statuses_url": "https://api.github.com/repos/rubengglez/cv/statuses/{sha}",
//     "languages_url": "https://api.github.com/repos/rubengglez/cv/languages",
//     "stargazers_url": "https://api.github.com/repos/rubengglez/cv/stargazers",
//     "contributors_url": "https://api.github.com/repos/rubengglez/cv/contributors",
//     "subscribers_url": "https://api.github.com/repos/rubengglez/cv/subscribers",
//     "subscription_url": "https://api.github.com/repos/rubengglez/cv/subscription",
//     "commits_url": "https://api.github.com/repos/rubengglez/cv/commits{/sha}",
//     "git_commits_url": "https://api.github.com/repos/rubengglez/cv/git/commits{/sha}",
//     "comments_url": "https://api.github.com/repos/rubengglez/cv/comments{/number}",
//     "issue_comment_url": "https://api.github.com/repos/rubengglez/cv/issues/comments{/number}",
//     "contents_url": "https://api.github.com/repos/rubengglez/cv/contents/{+path}",
//     "compare_url": "https://api.github.com/repos/rubengglez/cv/compare/{base}...{head}",
//     "merges_url": "https://api.github.com/repos/rubengglez/cv/merges",
//     "archive_url": "https://api.github.com/repos/rubengglez/cv/{archive_format}{/ref}",
//     "downloads_url": "https://api.github.com/repos/rubengglez/cv/downloads",
//     "issues_url": "https://api.github.com/repos/rubengglez/cv/issues{/number}",
//     "pulls_url": "https://api.github.com/repos/rubengglez/cv/pulls{/number}",
//     "milestones_url": "https://api.github.com/repos/rubengglez/cv/milestones{/number}",
//     "notifications_url": "https://api.github.com/repos/rubengglez/cv/notifications{?since,all,participating}",
//     "labels_url": "https://api.github.com/repos/rubengglez/cv/labels{/name}",
//     "releases_url": "https://api.github.com/repos/rubengglez/cv/releases{/id}",
//     "deployments_url": "https://api.github.com/repos/rubengglez/cv/deployments",
//     "created_at": "2019-10-15T17:38:26Z",
//     "updated_at": "2019-11-05T19:19:37Z",
//     "pushed_at": "2019-11-05T19:19:35Z",
//     "git_url": "git://github.com/rubengglez/cv.git",
//     "ssh_url": "git@github.com:rubengglez/cv.git",
//     "clone_url": "https://github.com/rubengglez/cv.git",
//     "svn_url": "https://github.com/rubengglez/cv",
//     "homepage": null,
//     "size": 534,
//     "stargazers_count": 0,
//     "watchers_count": 0,
//     "language": "TypeScript",
//     "has_issues": true,
//     "has_projects": true,
//     "has_downloads": true,
//     "has_wiki": true,
//     "has_pages": false,
//     "forks_count": 0,
//     "mirror_url": null,
//     "archived": false,
//     "disabled": false,
//     "open_issues_count": 0,
//     "license": null,
//     "forks": 0,
//     "open_issues": 0,
//     "watchers": 0,
//     "default_branch": "master"
//   },
